### ISSUE TITLE
healthcheck status - Starting

### ISSUE THREAD

**Issue by vecjh** [twitchax/nordvpn-proxy#4]
Hi,
I have the following status for this container in Portainer - `Starting`.

I ran healthcheck command from my concole and it turned that my system doesn't accept escaping quote. It works just w/o escapes.

**Comment by twitchax** [comment]
Are you using the base image, or are you editing this image?

**Comment by vecjh** [comment]
yes, I'm using your base image. and my system is Ubuntu 20.04. Notation that worked for me is:

`curl -m 10 -s https://api.nordvpn.com/vpn/check/full | jq -r '.["status"]'`

**Comment by twitchax** [comment]
It shouldn't matter, though, right?  That command runs inside the container.

**Comment by twitchax** [comment]
Fixed and pushed anyway.
