### ISSUE TITLE
doesn't work with latest "bubuntux/nordvpn"

### ISSUE THREAD

**Issue by vecjh** [twitchax/nordvpn-proxy#5]
I have cloned your repo and rebuilt the image. It pulled the newest version of "bubuntux/nordvpn". And containter doesn't work with it. The log says: `Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.`

Which version have you used to build your image?

**Comment by twitchax** [comment]
Ok, I will have to take a look at this.

**Comment by twitchax** [comment]
Looks like this is a NordVPN problem.

https://github.com/bubuntux/nordvpn/issues/97
