### ISSUE TITLE
Can't connect to SOCKS from windows client

### ISSUE THREAD

**Issue by deadcode0815** [twitchax/nordvpn-proxy#8]
Windows Host (running docker)
Maybe this is related to https://github.com/twitchax/nordvpn-proxy/issues/7

I  can't access the proxy from my windows client (hosting the docker container).

docker run -it --rm --cap-add NET_ADMIN -p 1080:1080 -e USER=<email> -e PASS='<pass>' -e TECHNOLOGY=NordLynx twitchax/nordvpn-proxy
also tried "docker run -it --rm --cap-add NET_ADMIN -p 0.0.0.0:1080:1080 -e USER=<email> -e PASS='<pass>' -e TECHNOLOGY=NordLynx twitchax/nordvpn-proxy" with no success

**Comment by twitchax** [comment]
Should be fixed on `latest` tag now.
